config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig

from users.views import LoginView, LogoutView, RegisterView, UserUpdateView, generate_new_password, succes, confirm

app_name = UsersConfig.name


urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='uupdate'),
    path('profile/genpassword/', generate_new_password, name='generatepassword'),
    path('register/succes/', succes, name='succes'),
    path('register/<uuid:uuid>/', confirm, name='confirm'),
]

users/models.py
import uuid as uuid
from django.contrib.auth.models import AbstractUser
from django.db import models

from catalog.models import NULLABLE


class User(AbstractUser):
    username = None

    email = models.CharField(max_length=25, unique=True)
    phone = models.CharField(max_length=10, **NULLABLE)
    country = models.CharField(max_length=25, **NULLABLE)
    avatar = models.ImageField(upload_to='users/', **NULLABLE)
    is_active = models.BooleanField(default=False)
    uuid = models.UUIDField(default=uuid.uuid4, editable=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from django import forms
from users.models import User



class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'phone', 'avatar', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
from django.conf import settings
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.core.mail import send_mail
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView

from users.forms import UserForm, ProfileForm
from users.models import User


class LoginView(BaseLoginView):
    template_name = 'users/login.html'


class LogoutView(BaseLogoutView):
    pass


class RegisterView(CreateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('users:succes')
    template_name = 'users/register.html'

    def form_valid(self, form):
        new_user = form.save()
        send_mail(
            subject='поздравляем с регистрацией',
            message=f'http://127.0.0.1:8000/users/register/{new_user.uuid}/',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[new_user.email]
        )
        return super().form_valid(form)


class UserUpdateView(UpdateView):
    model = User
    success_url = reverse_lazy('user:uupdate')
    form_class = ProfileForm

    def get_object(self, queryset=None):
        return self.request.user


def generate_new_password(request):
    print(request)
    new_pass = User.objects.make_random_password()
    send_mail(
        subject='новый пароль',
        message=f'{new_pass}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email]
    )
    request.user.set_password(new_pass)
    request.user.save()
    return redirect(reverse('users:login'))


def succes(request):
    return render(request, 'users/succes.html')


def confirm(request, uuid):
    user = get_object_or_404(User, uuid=uuid)
    user.is_active = True
    user.save()
    return render(request, 'users/confirm.html', {'uuid': uuid})

users/templates/users/confirm.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="card">

  аккаунт активирован
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="card">

    <form method="post">
        {% csrf_token %}
       {{ form.as_p }}
        <button type="submit">вход</button>
    </form>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="card">

    <form method="post">
        {% csrf_token %}
       {{ form.as_p }}
        <button type="submit">регистрация</button>
    </form>
</div>
{% endblock %}

users/templates/users/succes.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="card">

  на почту пришло письмо активируйте аккаунт пожалуйста
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}


<!--{% load crispy_forms_tags %}-->
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">профиль</h1>
</div>
<form method="post" class="form-floating" enctype="multipart/form-data">

        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">профиль</h4>
                </div>
                <div class="card-body">

                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">сохранить</button>
                        <a class="btn btn-success" href="{% url 'users:generatepassword' %}">сгенерировать пароль</a>


                </div>
            </div>
        </div>

 <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">версии</h4>
                </div>
                <div class="card-body">

                        {{ formset.management_form }}
                        {% for form in formset.forms %}

                        {{ form.as_p }}
                        {% endfor %}




                </div>
            </div>
        </div>
     </form>
    </div>
{% endblock %}