catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig
from catalog.views import ProductListView, ProductDetailView, ContactsCreateView, BlogListView, CreateNote, \
    BlogDetailView, UpdateNote, DeleteNote, ProductUpdateView, ProductCreateView, ProductDeleteView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('contacts/', ContactsCreateView.as_view(), name='contacts'),
    path('product/<int:pk>/update_product/', ProductUpdateView.as_view(), name='update_product'),
    path('product/<int:pk>/delete_product/', ProductDeleteView.as_view(), name='delete_product'),
    path('product/create_product/', ProductCreateView.as_view(), name='create_product'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product'),
    path('blog/', BlogListView.as_view(), name='blog'),
    path('blog/create/', CreateNote.as_view(), name='create'),
    path('blog/detail/<slug:slug>', BlogDetailView.as_view(), name='detail'),
    path('blog/update/<slug:slug>', UpdateNote.as_view(), name='update'),
    path('blog/delete/<int:pk>', DeleteNote.as_view(), name='delete'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig

from users.views import LoginView, LogoutView, RegisterView, UserUpdateView, generate_new_password, succes, confirm

app_name = UsersConfig.name


urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='uupdate'),
    path('profile/genpassword/', generate_new_password, name='generatepassword'),
    path('register/succes/', succes, name='succes'),
    path('register/<uuid:uuid>/', confirm, name='confirm'),
]

catalog/models.py
from django.db import models

from config import settings

NULLABLE = {'blank': True, 'null': True}


class Product(models.Model):
    product_name = models.CharField(max_length=64, verbose_name='имя продукта')
    product_description = models.CharField(max_length=128, verbose_name='описание продукта')
    product_image = models.ImageField(upload_to='images/products', verbose_name='изображение продукта', **NULLABLE)
    product_category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='категория продукта')
    product_price = models.FloatField(max_length=64, verbose_name='цена продукта')
    data_of_creation = models.DateField(verbose_name='дата создания продукта')
    data_of_modified = models.DateField(verbose_name='дата последнего изменения')

    version = models.CharField(max_length=10, **NULLABLE)

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE)

class VersionProduct(models.Model):
    product_pk = models.ForeignKey('Product', on_delete=models.CASCADE, **NULLABLE)
    name = models.CharField(max_length=10)
    is_active = models.BooleanField(default=False,)




class Category(models.Model):
    category_name = models.CharField(max_length=64, verbose_name='имя категории')
    category_description = models.CharField(max_length=128, verbose_name='описание категории')
    #created_at = models.CharField(max_length=4, verbose_name='test')

    def __str__(self):
        return self.category_name


class Contacts(models.Model):
    name = models.CharField(max_length=50)
    phone = models.CharField(max_length=10)
    message = models.CharField(max_length=10)


class BlogNotes(models.Model):
    title = models.CharField(max_length=100)
    slug = models.CharField(max_length=100, verbose_name='slug')
    content = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images/blog', **NULLABLE)
    date = models.DateField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    views = models.IntegerField(default=0)

catalog/forms.py
from django import forms

from catalog.models import Product, VersionProduct


class ProductForm(forms.ModelForm):
    exceptions = {'казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар'}

    class Meta:
        model = Product
        #fields = '__all__'
        exclude = ('owner',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)



        self.fields['version'].widget = forms.HiddenInput()
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    def clean_product_name(self):
        cleaned_data = self.cleaned_data.get('product_name')
        data = [cleaned_data]
        if self.exceptions.intersection(set(data)):
            raise forms.ValidationError('нельзя: казино, криптовалюта, крипта, биржа, дешево, бесплатно, обман, полиция, радар.')

        return cleaned_data

    def clean_product_description(self):
        cleaned_data = self.cleaned_data.get('product_description')
        data = [cleaned_data]
        if self.exceptions.intersection(set(data)):
            raise forms.ValidationError('нельзя: казино, криптовалюта, крипта, биржа, дешево, бесплатно, обман, полиция, радар.')

        return cleaned_data


class Version(forms.ModelForm):
    class Meta:
        model = VersionProduct
        fields = '__all__'

catalog/views.py
from django.forms import inlineformset_factory
from django.http import request
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify

from catalog.forms import ProductForm, Version
from catalog.models import Product, Contacts, BlogNotes, VersionProduct


class ProductListView(ListView):
    model = Product

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        #queryset = queryset.filter(owner=self.request.user)
        versions = VersionProduct.objects.filter(is_active=True,)
        for version in versions:
            version.product_pk.version = version.name
            version.product_pk.save()
        return queryset




class ContactsCreateView(CreateView):
    model = Contacts
    fields = ('name', 'message', 'phone')
    success_url = reverse_lazy('catalog:blog')


class ProductDetailView(DetailView):

    model = Product


class ProductUpdateView(UpdateView):
    model = Product
    #fields = '__all__'
    success_url = reverse_lazy('catalog:home')
    extra_context = {
        'title': 'обновить',
        'update': 'обновление продукта',
    }
    form_class = ProductForm

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        SubjectFormset = inlineformset_factory(Product, VersionProduct, form=Version, extra=1)
        if self.request.method == 'POST':

            context_data['formset'] = SubjectFormset(self.request.POST, instance=self.object)

        else:
            context_data['formset'] = SubjectFormset(instance=self.object)

        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

class ProductCreateView(CreateView):
    model = Product
    #fields = '__all__'
    success_url = reverse_lazy('catalog:home')
    extra_context = {
        'title': 'создание',
        'update': 'sozdat product',
    }
    form_class = ProductForm

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)

class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:home')


class BlogListView(ListView):
    model = BlogNotes

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_active=True)
        return queryset

class BlogDetailView(DetailView):
    model = BlogNotes

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views += 1
        self.object.save()

        return self.object




class CreateNote(CreateView):
    model = BlogNotes
    fields = ('title', 'content', 'image',)
    success_url = reverse_lazy('catalog:blog')

    extra_context = {
        'title': 'создать'
    }


    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)


class UpdateNote(UpdateView):
    model = BlogNotes
    fields = ('title', 'content', 'image',)
    #success_url = reverse_lazy('catalog:blog')
    extra_context = {
        'title': 'обновить'
    }

    def get_success_url(self):
        return reverse('catalog:detail', args=[self.kwargs.get('slug')])


class DeleteNote(DeleteView):
    model = BlogNotes
    success_url = reverse_lazy('catalog:blog')

catalog/templates/catalog/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:home' %}">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:blog' %}">блог</a>

        {% if user.is_authenticated %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:uupdate' %}">профиль</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">выход</a>
        {% else %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">вход</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">регистрация</a>
        {% endif %}
    </nav>
    {% include 'catalog/includes/inc_base.html' %}
</div>

{% block content %}
{% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'catalog:contacts' %}">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>


</body>
</html>

catalog/templates/catalog/blognotes_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}




        <div class="col-lg-3 col-md-6 col-sm-12">

                <div class="card-body">
                    <form method="post" class="form-floating" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">удалить</button>

    <a class="btn btn-primary mb-2" type="button" href="{% url 'catalog:blog' %}">отмена</a>

                    </form>


                </div>
            </div>

{% endblock %}

catalog/templates/catalog/blognotes_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
<div class="container">


          <div class="card shadow-sm">
            <img src="{% image_tag object.image %}" >
            <div class="card-body">
              <p class="card-text">{{ object.content }} ({{ object.slug }})</p>

            </div>
              <div>
               просмотры {{ object.views }}
</div>




  <div >
 
<!--    <button class="btn btn-primary" type="button">КУПИТЬ</button>-->
 </div>

</div>


{% endblock %}

catalog/templates/catalog/blognotes_form.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">создать запись</h1>
</div>


        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" class="form-floating" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">{{ title }}</button>
                    </form>


                </div>
            </div>
        </div>


    </div>
{% endblock %}

catalog/templates/catalog/blognotes_list.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">БЛОГ</p>
</div>
<div>
<a class="btn btn-primary mb-2" type="button" href="{% url 'catalog:create' %}">создать запись</a>
    </div>
<div class="container">

    <div class="row text-center">

        {% for object in object_list %}
        <div class="col-3 mb-2">

          <div class="card shadow-sm">
              <h1>{{ object.title }}</h1>
            <img src="{{ object.image|image_filter }}" >

            <div class="card-body">
              <p class="card-text">{{ object.content }}</p>
            </div>
  <div >
    <a class="btn btn-primary mb-2" type="button" href="{% url 'catalog:detail' object.slug %}">открыть</a>
 </div>
               <div >
    <a class="btn btn-primary mb-2" type="button" href="{% url 'catalog:update' object.slug %}">редактировать</a>
 </div>
                           <div >
    <a class="btn btn-primary mb-2" type="button" href="{% url 'catalog:delete' object.pk %}">удалить</a>
 </div>

          </div>
        </div>
{% endfor %}

    </div>

    {% endblock %}

catalog/templates/catalog/contacts_form.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" class="form-floating">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">отправить</button>
                    </form>


                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}




        <div class="col-lg-3 col-md-6 col-sm-12">

                <div class="card-body">
                    <form method="post" class="form-floating" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">удалить</button>

    <a class="btn btn-primary mb-2" type="button" href="{% url 'catalog:blog' %}">отмена</a>

                    </form>


                </div>
            </div>

{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
<div class="container">


          <div class="card shadow-sm">
            <img src="{% image_tag object.product_image %}" >
            <div class="card-body">
              <p class="card-text">{{ object.product_description }}</p>

            </div>

<div class="d-flex gap-2 justify-content-center py-2">

  <span class="badge text-bg-info rounded-pill">{{ object.product_category }}</span>

</div>

 <div class="card-header py-3">
            <h4 class="my-0 fw-normal">{{ object.product_price }}</h4>
          </div>
 {% if user.is_active == True %}
  <div >

    <a class="btn btn-primary" type="button" href="{% url 'catalog:update_product' object.pk %}">обновить продукт</a>

 </div>

                <div >

    <a class="btn btn-primary" type="button" href="{% url 'catalog:delete_product' object.pk %}">удалить продукт</a>
 </div>
{% endif %}
</div>


{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}


<!--{% load crispy_forms_tags %}-->
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ update }}</h1>
</div>
<form method="post" class="form-floating" enctype="multipart/form-data">

        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ update }}</h4>
                </div>
                <div class="card-body">

                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">{{ title }}</button>



                </div>
            </div>
        </div>

 <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">версии</h4>
                </div>
                <div class="card-body">

                        {{ formset.management_form }}
                        {% for form in formset.forms %}

                        {{ form.as_p }}
                        {% endfor %}




                </div>
            </div>
        </div>
     </form>
    </div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
     <div >
{% if user.is_active == True %}
    <a class="btn btn-primary mb-2" type="button" href="{% url 'catalog:create_product' %}">создать продукт</a>
{% endif %}
 </div>
</div>

<div class="container">

    <div class="row text-center">

        {% for object in object_list %}
        <div class="col-3 mb-2">

          <div class="card shadow-sm">
              <h1>{{ object.product_name }}</h1>
              {% if object.version is not None %}
              <h2>{{ object.version }}</h2>
              {% endif %}
            <img src="{{ object.product_image|image_filter }}" >

            <div class="card-body">
              <p class="card-text">{{ object.product_description|truncatechars:10 }}</p>
            </div>
  <div >
    <a class="btn btn-primary mb-2" type="button" href="{% url 'catalog:product' object.pk %}">Подробнее</a>
 </div>
          </div>
        </div>
{% endfor %}

    </div>

    {% endblock %}